# SPDX-License-Identifier: Apache-2.0
# Copyright 2024 Intel Corporation

name: Master
on:
  push:
    branches:
      - master
      - GHA-integration
  pull_request:

jobs:

  build-models:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'models/aether-2.1.x/go.mod'     
      - name: Build-models
        run: make models

  build-models-openapi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'models/aether-2.1.x/go.mod'
      - name: Build-models-openapi
        run: make models-openapi

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'models/aether-2.1.x/go.mod'
      - name: Build Docker image
        run: make docker-build

  hadolint:
    name: hadolint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dockerfile linter
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          recursive: true

  yang-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./models/aether-2.1.x
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'models/aether-2.1.x/go.mod'
      - name: yang-lint
        run: |
          pip install pyang
          make yang-lint

          
  license-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: reuse lint
        uses: fsfe/reuse-action@v3

  fossa-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: FOSSA scan
        uses: fossa-contrib/fossa-action@v3
        with:
          fossa-api-key: 6d304c09a3ec097ba4517724e4a4d17d
